apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-app-prod

resources:
- ../base
- hpa.yaml

patches:
- target:
    kind: Deployment
    name: devops-api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
      - name: ASPNETCORE_ENVIRONMENT
        value: "Production"

# USAR LATEST EN LUGAR DE v1.0.0
images:
- name: challenge.azurecr.io/devops-api
  newTag: "latest"  # ← CAMBIAR v1.0.0 por latest