# create-storage-canada.yml
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'TerraformStateResourceGroup'
  containerName: 'tfstate'
  location: 'canadacentral'  # ← Región que SÍ te funciona

steps:
- task: AzureCLI@2
  displayName: 'Create Storage Account in Canada Central'
  inputs:
    azureSubscription: 'MychallengeServiceConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      set -e
      
      echo "=== Usando región: $(location) ==="
      az account show
      
      echo "=== Creando Storage Account en Canadá ==="
      TIMESTAMP=$(date +%s)
      STORAGE_NAME="tfstate$TIMESTAMP"
      echo "Nuevo Storage Account: $STORAGE_NAME"
      
      # Crear Resource Group en Canadá
      az group create --name $(resourceGroupName) --location $(location) --tags Region=Canada || echo "RG ya existe"
      
      # Crear Storage Account en Canadá
      az storage account create \
        --resource-group $(resourceGroupName) \
        --name $STORAGE_NAME \
        --sku Standard_LRS \
        --encryption-services blob \
        --location $(location) \
        --allow-blob-public-access false
      
      echo "Esperando a que el Storage Account esté listo..."
      sleep 30
      
      # Crear container
      az storage container create \
        --name $(containerName) \
        --account-name $STORAGE_NAME \
        --auth-mode login
      
      echo ""
      echo "=== ✅ STORAGE ACCOUNT CREADO EN CANADÁ ==="
      echo "Resource Group: $(resourceGroupName)"
      echo "Storage Account: $STORAGE_NAME" 
      echo "Container: $(containerName)"
      echo "Location: $(location)"
      echo ""
      echo "=== 🔧 ACTUALIZA TU PIPELINE ==="
      echo "Variable: tfBackendStorage = $STORAGE_NAME"

- task: Bash@3
  displayName: 'Mostrar valores'
  inputs:
    targetType: 'inline'
    script: |
      echo "Storage Account creado exitosamente en Canadá"