# Pipeline principal completo
name: $(BuildID)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
      - develop

pr:
  branches:
    include:
      - master
      - develop

variables:
  - name: vmImage
    value: 'ubuntu-latest'
  - name: buildConfiguration
    value: 'Release'
  - name: solution
    value: 'Challenge.sln'
  - name: testProject
    value: 'Tests/**/*.csproj'
  - name: dockerfilePath
    value: 'Devops.Api/Dockerfile'
  - name: acrServiceConnection
    value: 'challengeserviceconnection'
  - name: acrName
    value: 'challenge.azurecr.io'
  - name: imageName
    value: 'devops-api'
  - name: azureServiceConnection
    value: 'MychallengeServiceConnection'
  - name: aksResourceGroup
    value: 'Challenge'
  - name: aksClusterName
    value: 'akschalle'
  - name: aksNamespaceDev
    value: 'devops-app-dev'
  - name: aksNamespaceProd
    value: 'devops-app-prod'

stages:
  # STAGE 1: BUILD
  - stage: Build
    displayName: 'Build Application'
    jobs:
    - job: Build
      displayName: 'Build and Package'
      pool:
        vmImage: $(vmImage)
      steps:
      - template: .azuredevops/templates/build-steps.yml

  # STAGE 2: TEST
  - stage: Test
    displayName: 'Run Tests'
    dependsOn: Build
    jobs:
    - job: Test
      displayName: 'Execute Automated Tests'
      pool:
        vmImage: $(vmImage)
      steps:
      - template: .azuredevops/templates/test-steps.yml

  # STAGE 3: DEPLOY DEVELOPMENT
  - stage: Deploy_Dev
    displayName: 'Deploy to Development'
    dependsOn: Test
    condition: |
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
          startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/')
        )
      )
    jobs:
    - deployment: Deploy_Development
      displayName: 'Deploy to Development Environment'
      pool:
        vmImage: $(vmImage)
      environment: 'Development'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: .azuredevops/templates/deploy-dev-steps.yml

  # STAGE 4: DEPLOY PRODUCTION
  - stage: Deploy_Prod
    displayName: 'Deploy to Production'
    dependsOn: Test
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
    - deployment: Deploy_Production
      displayName: 'Deploy to Production Environment'
      pool:
        vmImage: $(vmImage)
      environment: 'Production'
      strategy:
        runOnce:
          deploy:
            steps:
            - template: .azuredevops/templates/deploy-prod-steps.yml