# azure-pipelines-fix-backend.yml
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Create Storage Account Correctly'
  inputs:
    azureSubscription: 'MychallengeServiceConnection'  # Tu service connection que SÍ funciona
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      set -e
      
      echo "=== CREANDO STORAGE ACCOUNT ==="
      
      # El Resource Group YA existe, solo crear Storage Account
      RG_NAME="TerraformStateResourceGroup"
      CONTAINER_NAME="tfstate"
      
      # Generar nombre único
      TIMESTAMP=$(date +%s)
      STORAGE_NAME="tfstate$TIMESTAMP"
      echo "Storage Account name: $STORAGE_NAME"
      
      # Crear Storage Account con autenticación explícita
      echo "Creando Storage Account..."
      az storage account create \
        --resource-group $RG_NAME \
        --name $STORAGE_NAME \
        --sku Standard_LRS \
        --encryption-services blob \
        --location eastus \
        --allow-blob-public-access false \
        --https-only true
      
      # Esperar a que se propague
      echo "Esperando a que el Storage Account esté listo..."
      sleep 30
      
      # Crear container con autenticación login
      echo "Creando container..."
      az storage container create \
        --name $CONTAINER_NAME \
        --account-name $STORAGE_NAME \
        --auth-mode login
      
      echo ""
      echo "=== ✅ BACKEND CREADO EXITOSAMENTE ==="
      echo "Resource Group: $RG_NAME"
      echo "Storage Account: $STORAGE_NAME"
      echo "Container: $CONTAINER_NAME"
      echo ""
      echo "=== 🔧 ACTUALIZA TU PIPELINE PRINCIPAL ==="
      echo "Variable: tfBackendStorage = $STORAGE_NAME"

- task: Bash@3
  displayName: 'Verificar creación'
  inputs:
    targetType: 'inline'
    script: |
      echo "Verificación completada - Ahora actualiza tu pipeline principal"