# Pipeline principal - orquesta todas las etapas
name: $(BuildID)-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
      - master
      - develop
  paths:
    exclude:
    - README.md
    - .gitignore

pr:
  branches:
    include:
      - master
      - develop

# Incluir variables
variables:
  - template: .azuredevops/variables/global-variables.yml
  - template: .azuredevops/variables/build-variables.yml
  - template: .azuredevops/variables/deploy-variables.yml

stages:
  # Build Stage
  - template: .azuredevops/pipeline-templates/build-stage.yml

  # Test Stage  
  - template: .azuredevops/pipeline-templates/test-stage.yml

  # Development Deployment
  - template: .azuredevops/pipeline-templates/deploy-dev-stage.yml

  # Production Deployment
  - template: .azuredevops/pipeline-templates/deploy-prod-stage.yml