apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
  namespace: devops-app
  labels:
    app: devops-api
spec:
  type: LoadBalancer
  selector:
    app: devops-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP