apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-app-dev

resources:
- ../base

images:
- name: challenge.azurecr.io/devops-api
  newTag: develop-latest

patches:
- target:
    kind: Deployment
    name: devops-api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: 50m
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 64Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 200m
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 256Mi
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ASPNETCORE_ENVIRONMENT
        value: "Development"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: LOG_LEVEL
        value: "Debug"