apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-app-dev

resources:
- ../base

patches:
- target:
    kind: Deployment
    name: devops-api
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi

images:
- name: challenge.azurecr.io/devops-api
  newTag: develop-latest